decorator:
  datasource:
    exclude-beans: datasource

spring:
  datasource:
    url: jdbc:mysql://192.168.0.34:3306/lezhin?useSSL=false&serverTimezone=UTC
    username: admin
    password: lezhin1234!@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true


logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs

cors:
  allow:
    origin: "*"
    method: "GET, POST, PUT, PATCH"

servers:
  domain:
    local: "http://localhost:8080"
jwt:
  secret: "lezhinApiSecretKeylezhinApiSecretKeylezhinApiSecretKeylezhinApiSecretKeylezhinApiSecretKey"